### PR TITLE
Project initialization

### PR DESCRIPTION
**Pull request by j8r**

### CODE REVIEW

**Comment by j8r** [comment]
What's remains to do:
- JSON report
- Markdown report
- configurable IO
- more benchs

**Comment by konung** [comment]
Excellent! Looks good to me

**Comment by j8r** [comment]
Not sure to add this dependency @icyleaf . Despite not being a fan of the old school `Makefile`, once the binary is built, it can be executed how many and times we want how we wish. Adding another layer isn't necessary, at least for now.

**Comment by j8r** [comment]
JSON reports added :)
I've taken the fields from the stdlib
```json
{
  "Array": {
    "bsearch_vs_find": [
      {
        "label": "Array#find",
        "cycles": 1605,
        "size": 50,
        "mean": 16025.927200577693,
        "variance": 40462.44722321981,
        "stddev": 201.15279571315884,
        "relative_stddev": 1.2551710312643116,
        "slower": 2455.4261809832574,
        "bytes_per_op": 0
      },
   ...
```

**Pull request merged**
